site_name: Cline Automation Extension
site_description: Documentation for VSCode extension that automates Cline interactions using Claude Sonnet
site_url: https://karimstekelenburg.github.io/cline-automation/
repo_url: https://github.com/karimstekelenburg/cline-automation
repo_name: karimstekelenburg/cline-automation

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.follow
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Project Overview:
    - Context: project-context.md
    - Functional Requirements: functional-requirements.md
    - Technical Requirements: technical-requirements.md
  - Technical Documentation:
    - Architecture: architectural-design.md
    - Implementation Plan: implementation-plan.md
  - Progress:
    - Progress Log: progress-log.md
    - Scratchpad: scratchpad.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - meta
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/karimstekelenburg/cline-automation